import Navbar from "@/components/UI/Restaurant/Navbar";

export const metadata = {
  title: 'Ommitus Restuarant Portal',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
      </body>
    </html>
  )
}
