import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>

        <Toaster />
        {children}
      </body>
    </html>
  )
}
